name: node-js-app

on:
  push:
    branches: [ main ]
    paths: .github/workflows/CiCd.yml
  pull_request:
    branches:  none # [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build-deploy-aks:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPOSITORY: atiftaqi # name of Docker Hub container Registry
      IMAGE_NAME: node-js-app
      IMAGE_TAG: ${{ github.run_number }} # $GITHUB_RUN_NUMBER
      
      CLUSTER_NAME: azure-kubernetes-cluster-atif
      RESOURSE_GROUP: aks-atif
    
    steps:

    - name: Git Checkout
      uses: actions/checkout@v2

  
 #   - name: Build Docker Image
  #    run:
    #    docker build ./Docker-Kubernetes/ --file ./Docker-Kubernetes/Dockerfile --tag $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER --build-arg=token=ZGEzNTQ5Y2QyNjAx --no-cache

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      continue-on-error: true
      with:
        image-ref: 'docker.io/${{ env.DOCKER_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}'
        format: 'table'
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'MEDIUM,HIGH,CRITICAL'
  
    - name: Login to image repository
      if: github.ref_type == 'tag'
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_REPOSITORY }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  
    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: atiftaqi/node-js-app
        registry: docker.io
        username: ${{ secrets.DOCKER_REPOSITORY }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - uses: Azure/k8s-deploy@v4
      with:
       namespace: 'docker-deployment'
       run: kubectl run node-js-app –-image=atiftaqi/node-js-app  –-port=3000 –-generator=run/v1

      
     
